# Generated by Django 2.2.3 on 2019-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='categorias',
            field=models.ManyToManyField(to='blog.categoria'),
        ),
    ]
