# Generated by Django 2.2.3 on 2019-08-14 22:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entrada_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
